leftnav:
- identifier: 22f15593-ee8d-8ceb-a068-46017e1a0c18
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 30ee943b-ced5-bffc-7aa8-1853fe1331ed
  name: Instructor Insights
  url: /pages/instructor-insights/
  weight: 20
- identifier: f3c30597-e98a-7413-ca9f-bcc66290f930
  name: Engaging Students in Archive-based Research
  parent: 30ee943b-ced5-bffc-7aa8-1853fe1331ed
  url: /pages/instructor-insights/engaging-students-in-archive-based-research
  weight: 30
- identifier: 61e1fd4a-1e9e-3783-5cc4-8b3cb65e4c71
  name: Infusing the Course with Multiple Voices
  parent: 30ee943b-ced5-bffc-7aa8-1853fe1331ed
  url: /pages/instructor-insights/infusing-the-course-with-multiple-voices
  weight: 40
- identifier: 14fa2451-e10b-a6b3-0aba-adfbf955056f
  name: Teaching Students how to be Scholars
  parent: 30ee943b-ced5-bffc-7aa8-1853fe1331ed
  url: /pages/instructor-insights/teaching-students-how-to-be-scholars
  weight: 50
- identifier: 27b475ff-e089-aa88-09d8-65a0341aa2a5
  name: Readings and Discussion Schedule
  url: /pages/readings-and-discussion-schedule
  weight: 60
- identifier: f3dc2223-85bd-d983-1a09-140a7992f68e
  name: Assignments
  url: /pages/assignments
  weight: 70
